site_name: 笃实科协
repo_url: https://github.com/dssast-tech/dssast-tech.github.io
repo_name: GitHub
nav:
  - 首页:
    - 欢迎: index.md
  - 课程笔记: 
    - 前言: course-notes/index.md
  - 技术分享: 
    - 前言: tech-sharing/index.md
  - 活动通知: 
    - 前言: activities/index.md
  - 选课导引: course-guide-redirect.md
  - 算力平台: compute-platform-redirect.md
  - 线上社区: community-redirect.md
theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
    - search.sticky
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.path
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换到深色
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dssast-tech
      name: 笃实科协 GitHub 组织